
name: Daily release

on:
  workflow_dispatch:
  schedule:
    - cron: '33 0 * * *'

env:
  workflowRepo: dixyes-bot/lwmbs-play
  workflowRev: play

jobs:
  build-linux:
    # this donot support use env context
    uses: dixyes-bot/lwmbs-play/.github/workflows/linux-new.yml@play
    permissions:
      contents: write
    with:
      uploadRelease: true
      # i just cannot get these in reusable workflow, so do this
      workflowRepo: ${{ env.workflowRepo }}
      workflowRev: ${{ env.workflowRev }}
