
name: Daily release

on:
  workflow_dispatch:
  schedule:
    - cron: '33 0 * * *'

jobs:
  build-linux:
    uses: dixyes-bot/lwmbs-play/.github/workflows/linux-new.yml@play
    with:
      uploadRelease: true
      workflowRepo: dixyes-bot/lwmbs-play
      workflowRev: ${{ github.job_workflow_sha }}
